// @flow

import TranslationKeys from './TranslationKeys';
import { PROPERTY_CONSTS } from './SchemaConstants';

export default {
  [TranslationKeys.ADULT_MEDIA]: PROPERTY_CONSTS.ADULT_MEDIA,
  [TranslationKeys.BG_AUDIO_DAY]: PROPERTY_CONSTS.BG_AUDIO_DAY,
  [TranslationKeys.BG_AUDIO_NIGHT]: PROPERTY_CONSTS.BG_AUDIO_NIGHT,
  [TranslationKeys.BG_MEDIA_OPTIONS]: PROPERTY_CONSTS.BG_TV_DAY,
  [TranslationKeys.BOOK_TYPE_OPTIONS]: PROPERTY_CONSTS.PRIMARY_BOOK_TYPE,
  [TranslationKeys.CAREGIVER_OPTIONS]: PROPERTY_CONSTS.CAREGIVER,
  [TranslationKeys.CLOCK_FORMATS]: PROPERTY_CONSTS.CLOCK_FORMAT,
  [TranslationKeys.MEDIA_ACTIVITY_OPTIONS]: PROPERTY_CONSTS.PRIMARY_MEDIA_ACTIVITY,
  [TranslationKeys.MEDIA_AGE_OPTIONS]: PROPERTY_CONSTS.PRIMARY_MEDIA_AGE,
  [TranslationKeys.NON_TYPICAL_DAY_REASONS]: PROPERTY_CONSTS.NON_TYPICAL_DAY_REASON,
  [TranslationKeys.NON_TYPICAL_SLEEP_OPTIONS]: PROPERTY_CONSTS.NON_TYPICAL_SLEEP_PATTERN,
  [TranslationKeys.PRIMARY_ACTIVITIES]: PROPERTY_CONSTS.ACTIVITY_NAME,
  [TranslationKeys.SLEEP_ARRANGEMENT_OPTIONS]: PROPERTY_CONSTS.SLEEP_ARRANGEMENT,
  [TranslationKeys.TYPICAL_DAY_CHOICES]: PROPERTY_CONSTS.TYPICAL_DAY_FLAG,
  [TranslationKeys.WAKE_UP_COUNT_OPTIONS]: PROPERTY_CONSTS.WAKE_UP_COUNT,
  [TranslationKeys.WEEKDAY_OPTIONS]: PROPERTY_CONSTS.DAY_OF_WEEK,
};
