// flow-typed signature: 7bf130cc95ac073569f7b4dd9838195c
// flow-typed version: <<STUB>>/react-dom_v16.13.1/flow_v0.125.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom' {
  declare module.exports: any;
}
